import { Badge, Box, Text, VStack } from '@chakra-ui/react'

interface Props {
  image: string
  createdBy?: string
  showCreator?: boolean
  typeUser: number
  text: string
  tags: string
}
export default function CommunityCardV({
  image,
  createdBy = 'Taggy',
  showCreator = true,
  typeUser,
  tags,
  text,
}: Props) {
  return (
    <Box
      bg={'taggyDark.50'}
      boxShadow='0 4px 10px rgba(0,0,0,0.8)'
      rounded={6}
      overflow={'hidden'}
      position={'relative'}
    >
      <Box
        pos={'absolute'}
        right={0}
      >
        <Badge
          variant='solid'
          background={'rgba(9,9,9,0.4)'}
          color={'white'}
          m={4}
          rounded={6}
        >
          {typeUser === 1 && 'Regular User'}
          {typeUser === 2 && 'Content Creator'}
          {typeUser === 3 && 'Business'}
        </Badge>
      </Box>
      <VStack
        justifyContent={'flex-end'}
        alignItems={'flex-start'}
        w={'full'}
        // aspectRatio={'9/16'}
        backgroundColor={'taggyDark.50'}
        rounded={6}
        overflow={'hidden'}
        sx={{
          backgroundImage: `url(${image})`,
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repet',
        }}
      >
        <Box
          pt={12}
          sx={{
            background: 'linear-gradient(to bottom, rgb(0,0,0,0), rgb(0,0,0,0.4), rgb(0,0,0,0.6),  rgb(0,0,0,0.8))',
          }}
        >
          <Text
            whiteSpace={'pre-line'}
            color={'white'}
            p={4}
            fontSize='md'
            textShadow={'0px 0px 1px rgba(0,0,0)'}
          >
            {text}
          </Text>
          <Text
            px={4}
            pb={4}
            fontSize='md'
            fontWeight={'semibold'}
            color={'white'}
            textShadow={'0px 0px 1px rgba(0,0,0)'}
          >
            {tags}
          </Text>
        </Box>
      </VStack>
      {showCreator && (
        <Box
          px={4}
          py={1}
          fontSize={'xs'}
          color={'taggyGray.100'}
        >
          Generated by {createdBy ?? 'Taggy'}
        </Box>
      )}
    </Box>
  )
}
